export const recipes = [
  {
    title: "Soo-iga Sapi Special",
    description: "Iga sapi bakar dengan bumbu kecap pedas manis yang meresap.",
    creator: "Bundikas",
    creatorType: "Chef",
    cookingTime: "45 min",
    category: "special",
    isPrivate: false,
    rating: 4.8,
    calories: "450 kkal",
    ingredients: ["500g Iga Sapi", "5 siung Bawang Putih", "3 sdm Kecap Manis", "Cabai Rawit", "Jeruk Nipis", "Garam & Lada"],
    steps: ["Rebus iga hingga empuk.", "Tumis bawang dan cabai.", "Masukkan iga, bumbui kecap, garam, lada.", "Panggang sambil oles bumbu.", "Sajikan dengan jeruk nipis."],
  },
  {
    title: "Salmon Teriyaki Sehat",
    description: "Menu sehat omega-3 dengan saus teriyaki rendah gula.",
    creator: "Mundikas",
    creatorType: "Chef",
    cookingTime: "20 min",
    category: "healthy",
    isPrivate: false,
    rating: 4.9,
    calories: "320 kkal",
    ingredients: ["200g Salmon", "Saus Teriyaki", "Brokoli", "Wijen", "Minyak Zaitun"],
    steps: ["Marinasi salmon 10 menit.", "Blansir brokoli 2 menit.", "Panaskan pan.", "Panggang salmon 3-4 menit per sisi.", "Sajikan dengan wijen."],
  },
  {
    title: "Puding Mangga Susu",
    description: "Dessert lembut mangga harum manis dan susu segar.",
    creator: "Subarkusak",
    creatorType: "Chef",
    cookingTime: "60 min",
    category: "dessert",
    isPrivate: false,
    rating: 4.7,
    calories: "210 kkal",
    ingredients: ["2 Mangga", "500ml Susu", "Agar-agar", "Gula"],
    steps: ["Blender mangga.", "Masak agar + gula + susu sampai mendidih.", "Masukkan jus mangga.", "Tuang ke cetakan.", "Dinginkan 1 jam."],
  },
  {
    title: "Nasi Goreng Kampung",
    description: "Nasi goreng autentik dengan terasi dan telur orak-arik.",
    creator: "Masekah",
    creatorType: "Chef",
    cookingTime: "30 min",
    category: "traditional",
    isPrivate: false,
    rating: 4.6,
    calories: "500 kkal",
    ingredients: ["Nasi dingin", "Terasi", "Bawang Merah", "Bawang Putih", "Telur", "Kecap Asin"],
    steps: ["Tumis bumbu + terasi.", "Orak-arik telur.", "Masukkan nasi.", "Bumbui kecap asin.", "Aduk sampai harum."],
  },
  {
    title: "Sup Ayam Rumahan",
    description: "Sup hangat sederhana untuk menu sehari-hari.",
    creator: "Bu Tati",
    creatorType: "Home Cook",
    cookingTime: "35 min",
    category: "all",
    isPrivate: false,
    rating: 4.4,
    calories: "280 kkal",
    ingredients: ["Ayam", "Wortel", "Kentang", "Daun Bawang", "Bawang Putih", "Garam"],
    steps: ["Rebus ayam.", "Masukkan sayur.", "Bumbui.", "Masak hingga empuk.", "Taburi daun bawang."],
  },
];
